//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctus.CustomBP.WorkFlowCheckService4Test {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="webservices.PRWorkflow.weaver.com.cn", ConfigurationName="WorkFlowCheckService4Test.PRWorkflowPortType")]
    public interface PRWorkflowPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string PRCheck(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> PRCheckAsync(string in0, string in1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PRWorkflowPortTypeChannel : Auctus.CustomBP.WorkFlowCheckService4Test.PRWorkflowPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PRWorkflowPortTypeClient : System.ServiceModel.ClientBase<Auctus.CustomBP.WorkFlowCheckService4Test.PRWorkflowPortType>, Auctus.CustomBP.WorkFlowCheckService4Test.PRWorkflowPortType {
        
        public PRWorkflowPortTypeClient() {
        }
        
        public PRWorkflowPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PRWorkflowPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PRWorkflowPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PRWorkflowPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PRCheck(string in0, string in1) {
            return base.Channel.PRCheck(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> PRCheckAsync(string in0, string in1) {
            return base.Channel.PRCheckAsync(in0, in1);
        }
    }
}
